import {Match2,ARMIES,ARMY_HELP,seal,other} from './chess2-engine.js';
const $=id=>document.getElementById(id),colorName=c=>c==='w'?'White':'Black';
const words='acorn amber apple arrow beach berry bloom breeze brook candle castle cedar cherry cloud clover comet coral crane creek crown daisy dawn delta dragon dream drift eagle earth ember falcon fern field flame flower forest frost galaxy garden glade globe golden grape grove harbor hazel honey island ivory jasper jewel jungle kitten lagoon lemon lilac lotus lunar mango maple marble meadow melon meteor mint moon moss nectar night ocean olive opal orbit orchid otter panda peach pearl pebble petal planet plume pocket pollen pond prism purple quartz rabbit raven reef ribbon ripple river robin rocket rose ruby saddle safari sage satin seal shadow shell silver snow solar spark spice spring spruce square star stone storm stream sugar summit sunset swift temple tiger timber torch trail tulip turtle valley velvet violet walnut water whale willow winter wonder yellow zebra'.split(' ');
const names={p:'pawn',n:'knight',b:'bishop',r:'rook',q:'queen',k:'king'},symbols={p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'};
const special={nemesis:{q:'Nemesis',p:'Nemesis pawn'},empowered:{r:'Empowered rook',n:'Empowered knight',b:'Empowered bishop',q:'Short queen'},reaper:{r:'Ghost',q:'Reaper'},kings:{k:'Warrior king'},animals:{r:'Elephant',n:'Wild horse',b:'Tiger',q:'Jungle queen'}};
let match=new Match2(),mode='idle',role='host',ready=false,flipped=false,selected=null,promotion=null,pending=false;
let peer=null,connection=null,generation=0,deadline=null,replyTimer=null,room='',loadingPeer,lastSeen=0,lastBeat=0;
let queue=Promise.resolve(),secrets={},autoRevealing=false,localViewer=null,privacyKey='',busy=false;
const game=()=>match.game,me=()=>match.color(role),active=()=>mode==='local'||(mode==='online'&&ready);
const myTurn=()=>active()&&!pending&&!busy&&!game().result&&game().phase==='move'&&(mode==='local'||game().turn===me());
function message(text){$('connection').textContent=text;}
function pname(p){return special[game().armies[p.c]]?.[p.t]||names[p.t]}
function currentDecision(){const g=game();if(g.phase==='army')return ['w','b'].filter(c=>!g.commit[c]);if(g.phase==='offer')return [g.duel.defender];if(g.phase==='bid')return ['w','b'].filter(c=>!g.duel.commit[c]);if(g.phase==='bluff')return [g.duel.attacker];return []}
function viewer(){if(mode==='online')return me();return currentDecision()[0]||game().turn}
function closePromotion(){promotion=null;if($('promotion').open)$('promotion').close()}
function button(text,fn,disabled=false){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.onclick=fn;return b}
function decisionUI(){
 const g=game(),who=viewer(),actions=$('decisionActions');actions.replaceChildren();$('decisions').hidden=mode==='idle'||!!g.result||g.phase==='move';
 const can=active()&&!pending&&!busy;
 if(mode==='local'&&g.phase!=='move'&&!g.result){const key=`${match.round}:${g.phase}:${g.duel?.id||0}:${who}`;if(privacyKey!==key){privacyKey=key;localViewer=null;$('privacyTitle').textContent=`Pass the device to ${colorName(who)}`;$('privacy').hidden=false;}}
 else $('privacy').hidden=true;
 if(g.phase==='army'){
  $('decisionTitle').textContent='Choose your army';$('decisionHelp').textContent=g.commit[who]?'Army locked. Waiting for the other player.':'Choose secretly. Both armies reveal after both players lock in.';
  if(!g.commit[who]){const select=document.createElement('select');select.id='armyChoice';select.setAttribute('aria-label','Choose army');for(const [id,label] of Object.entries(ARMIES)){const option=document.createElement('option');option.value=id;option.textContent=label;option.disabled=!!g.locked[who]&&g.locked[who]!==id;select.append(option)}select.value=g.locked[who]||'classic';select.disabled=!can||!!g.locked[who];const help=document.createElement('p');help.className='small';const describe=()=>{help.textContent=ARMY_HELP[select.value]+(g.locked[who]?' You won the previous game, so your army stays the same.':'')};select.onchange=describe;describe();actions.append(select,help,button('Lock army',()=>lockSecret('army',select.value,who),!can));}
 }else if(g.phase==='offer'){
  const d=g.duel;$('decisionTitle').textContent=`${colorName(d.defender)}: challenge this capture?`;$('decisionHelp').textContent=`${pname(g.transaction.piece)} captures ${pname(g.board[d.target])} on ${d.target}. Duel entry costs ${d.cost} stone${d.cost===1?'':'s'}. Your piece is lost either way; winning also removes the attacker.`;
  if(who===d.defender){actions.append(button('Allow capture',()=>act({type:'duelChoice',accept:false},who),!can),button(`Duel${d.cost?' · pay 1 stone':''}`,()=>act({type:'duelChoice',accept:true},who),!can));}else actions.append(button('Waiting for defender…',()=>{},true));
 }else if(g.phase==='bid'){
  const d=g.duel;$('decisionTitle').textContent='Secret stone bid';$('decisionHelp').textContent=`${colorName(who)}: bid 0–2 stones. Ties favor the attacker. Bids cannot change after locking.`;
  if(d.commit[who])actions.append(button('Bid locked · waiting…',()=>{},true));else for(let i=0;i<=Math.min(2,g.stones[who]);i++)actions.append(button(`Bid ${i}`,()=>lockSecret('bid',i,who),!can));
 }else if(g.phase==='bluff'){
  $('decisionTitle').textContent='Bluff called: both bid zero';$('decisionHelp').textContent=`${colorName(g.duel.attacker)} chooses a reward.`;
  if(who===g.duel.attacker){actions.append(button('Gain 1 stone',()=>act({type:'bluff',choice:'gain'},who),!can),button('Opponent loses 1 stone',()=>act({type:'bluff',choice:'drain'},who),!can));}
 }
}
function draw(){
 const g=game(),focus=document.activeElement?.dataset?.square,frag=document.createDocumentFragment();const legal=selected&&myTurn()?g.legal(selected):[];
 for(let row=0;row<8;row++)for(let col=0;col<8;col++){
  const x=flipped?7-col:col,y=flipped?row:7-row,s=String.fromCharCode(97+x)+(y+1),p=g.board[s],possible=legal.find(m=>m.to===s&&!m.whirlwind);
  const b=document.createElement('button');b.dataset.square=s;b.className='square'+((x+y)%2===0?' dark':'')+(row===3?' midline':'')+(selected===s?' selected':'')+(possible?' legal':'')+(possible?.captures.length?' capture':'')+([g.last?.from,g.last?.to].includes(s)?' last':'');b.disabled=!myTurn();b.setAttribute('aria-label',`${s}: ${p?colorName(p.c)+' '+pname(p):'empty'}${possible?', legal move':''}`);b.setAttribute('aria-pressed',String(selected===s));
  if(p){const span=document.createElement('span');span.className='piece '+(p.c==='w'?'whitePiece':'blackPiece');span.textContent=symbols[p.t];span.setAttribute('aria-hidden','true');b.append(span);if(special[g.armies[p.c]]?.[p.t]){const tag=document.createElement('span');tag.className='armyTag';tag.textContent=pname(p).split(' ').map(s=>s[0]).join('');tag.title=pname(p);b.append(tag)}}
  if(row===7||col===0){const label=document.createElement('span');label.className='coord';label.textContent=s;b.append(label)}b.onclick=()=>select(s);frag.append(b);
 }
 $('board').replaceChildren(frag);if(focus)$('board').querySelector(`[data-square="${focus}"]`)?.focus({preventScroll:true});
 $('identity').textContent=mode==='idle'?'Choose a game':mode==='local'?`Same device · Round ${match.round}`:`You are ${colorName(me())} · Round ${match.round}`;
 $('status').textContent=g.result?(g.result.winner?`${colorName(g.result.winner)} wins — ${g.result.reason}.`:`Draw — ${g.result.reason}.`):!active()?'Create or join a room to start.':g.phase==='army'?'Choose armies to begin.':g.phase!=='move'?'Capture paused for a duel.':`${colorName(g.turn)} to move${g.kingTurn?' · optional king turn':''}${g.checked(g.turn)?' — CHECK!':''}`;
 $('boardHint').textContent=selected&&g.board[selected]?pname(g.board[selected])+': '+ARMY_HELP[g.armies[g.board[selected].c]]:'Select a piece, then a highlighted square. The dashed line is the invasion boundary.';
 $('stones').textContent=`White: ${g.stones.w} stones · Black: ${g.stones.b} stones`;
 $('armies').textContent=g.armies.w?`White: ${ARMIES[g.armies.w]} · Black: ${ARMIES[g.armies.b]}`:'Armies stay hidden until both players lock in.';
 $('create').disabled=mode!=='idle';$('join').disabled=mode!=='idle';$('local').disabled=mode!=='idle';$('roomCode').readOnly=mode!=='idle';$('leave').hidden=mode==='idle';$('flip').disabled=mode==='idle';$('resign').disabled=!active()||!!g.result||pending||busy;
 $('rematch').disabled=!active()||!g.result||pending||busy||match.votes.includes(role);$('rematch').textContent=match.votes.includes(role)?'Waiting for friend…':match.votes.length?'Accept rematch':'Request rematch';
 $('whirlwind').hidden=!legal.some(m=>m.whirlwind);$('whirlwind').disabled=!myTurn();$('skip').hidden=!g.kingTurn||g.phase!=='move';$('skip').disabled=!myTurn();
 $('moves').textContent=g.log.length?g.log.slice(-100).join('\n'):'Your moves and duels will appear here.';$('moves').scrollTop=$('moves').scrollHeight;
 decisionUI();
}
function select(s){if(!myTurn())return;if(selected){const candidates=game().legal(selected).filter(m=>m.to===s&&!m.whirlwind);if(candidates.length){if(candidates.some(m=>m.promotion)){promotion={from:selected,to:s};document.querySelectorAll('[data-piece]').forEach(b=>{b.disabled=!candidates.some(m=>m.promotion===b.dataset.piece)});$('promotion').showModal();return}act({type:'move',from:selected,to:s});return}}selected=selected===s?null:game().board[s]?.c===game().turn?s:null;draw()}
function actor(c){return match.color('host')===c?'host':'guest'}
function secretKey(kind,c){return `${match.round}:${kind}:${kind==='bid'?game().duel.id:0}:${c}`}
async function lockSecret(kind,value,c){if(busy||pending)return;busy=true;draw();const salt=Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');const key=secretKey(kind,c);const context=`round${match.round}:`+(kind==='army'?'army':'duel'+game().duel.id);try{const hash=await seal(value,salt,context);secrets[key]={value,salt,sent:false};busy=false;await act({type:kind==='army'?'armyCommit':'bidCommit',hash},c)}catch{busy=false;message('Could not lock your choice. Use HTTPS and try again.');draw()}}
async function revealSecrets(){if(autoRevealing||!active()||pending||busy)return;autoRevealing=true;try{
  const g=game(),kind=g.phase==='army'?'army':g.phase==='bid'?'bid':null;if(!kind)return;const commits=kind==='army'?g.commit:g.duel.commit,reveals=kind==='army'?g.reveal:g.duel.reveal;if(!commits.w||!commits.b)return;
  for(const c of mode==='local'?['w','b']:[me()]){const secret=secrets[secretKey(kind,c)];if(secret&&!secret.sent&&!reveals[c]){secret.sent=true;await act({type:kind==='army'?'armyReveal':'bidReveal',value:secret.value,salt:secret.salt},c);}}
 }finally{autoRevealing=false}}
function send(data){try{if(connection?.open){connection.send(data);return true}}catch{}return false}
function stop(){generation++;clearTimeout(deadline);clearTimeout(replyTimer);const old=peer;peer=null;connection=null;ready=false;pending=false;busy=false;secrets={};privacyKey='';$('privacy').hidden=true;$('copy').disabled=true;closePromotion();if(old)old.destroy();}
function lost(text){stop();message(text+' Leave the game to try a new room.');draw()}
function sendState(){if(!send({type:'state',version:24,state:match.snapshot()}))lost('Connection lost.')}
async function act(action,c){if(!active()||pending||busy)return;const g=game(),request={...action,round:match.round,ply:g.ply,duel:g.duel?.id};selected=null;closePromotion();
 if(mode==='local'){if(action.type==='rematch'){await match.apply(request,'host');await match.apply(request,'guest');secrets={};}else await match.apply(request,actor(c||g.turn));draw();queueMicrotask(revealSecrets);}
 else if(role==='host'){queue=queue.then(async()=>{const before=match.round;if(await match.apply(request,'host')){if(before!==match.round){secrets={};flipped=me()==='b'}sendState();draw();queueMicrotask(revealSecrets)}});await queue;}
 else{pending=true;if(!send({type:'action',version:24,action:request})){lost('Connection lost.');return}replyTimer=setTimeout(()=>lost('Your friend stopped responding.'),20000);draw();}
}
async function stateReceived(s){try{if(!s||s.revision<match.revision)throw Error('stale');const next=await Match2.restore(s),before=match.round;match=next;if(before!==match.round){secrets={};flipped=me()==='b'}ready=true;pending=false;clearTimeout(deadline);clearTimeout(replyTimer);selected=null;closePromotion();message(`Connected · Room: ${room}`);draw();queueMicrotask(revealSecrets)}catch{lost('The games could not stay in sync.')}}
function attach(c,token){connection=c;c.on('open',()=>{if(token!==generation)return;lastSeen=Date.now();send({type:'hello',version:24})});c.on('data',data=>{if(token!==generation||!data||typeof data!=='object')return;if(data.version!==24){lost('Different game version. Both refresh and try again.');return}lastSeen=Date.now();if(data.type==='ping'){send({type:'pong',version:24});return}if(data.type==='pong')return;
 queue=queue.then(async()=>{if(token!==generation)return;if(data.type==='hello'&&role==='host'&&!ready){ready=true;clearTimeout(deadline);message(`Connected · Room: ${room}`);sendState();draw();return}if(role==='guest'&&data.type==='state'){await stateReceived(data.state);return}if(role==='host'&&ready&&data.type==='action'){const before=match.round;await match.apply(data.action,'guest');if(before!==match.round){secrets={};flipped=me()==='b'}selected=null;sendState();draw();queueMicrotask(revealSecrets);}}).catch(()=>lost('Invalid game message.'));
 });c.on('close',()=>{if(token===generation)lost('Your friend disconnected.')});c.on('error',()=>{if(token===generation)lost('Could not connect to your friend.')});}
function loadPeer(){if(window.Peer)return Promise.resolve();if(!loadingPeer)loadingPeer=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/peerjs@1.5.5/dist/peerjs.min.js';script.onload=resolve;script.onerror=()=>{script.remove();loadingPeer=null;reject(Error('load'))};document.head.append(script)});return loadingPeer}
function randomWord(used){const available=words.filter(w=>!used.includes(w));let n;const limit=Math.floor(4294967296/available.length)*available.length;do{n=crypto.getRandomValues(new Uint32Array(1))[0]}while(n>=limit);return available[n%available.length]}
async function connect(host,word='',used=[]){stop();const token=generation;match=new Match2();mode='online';role=host?'host':'guest';flipped=!host;room='';queue=Promise.resolve();message('Connecting…');draw();deadline=setTimeout(()=>{if(token===generation)lost('Connection timed out. Check the word or try another network.')},25000);try{await loadPeer();if(token!==generation)return;room=host?randomWord(used):word;if(host)used.push(room);peer=new Peer(host?'adlai-chess2-'+room:undefined,{secure:true,debug:0});peer.on('open',()=>{if(token!==generation)return;if(host){clearTimeout(deadline);$('roomCode').value=room;$('copy').disabled=false;message(`Room ready: ${room}. Send the word or invite to your friend.`)}else attach(peer.connect('adlai-chess2-'+room,{reliable:true,serialization:'json'}),token)});peer.on('connection',c=>{if(token!==generation||!host||connection){c.on('open',()=>c.close());return}attach(c,token);deadline=setTimeout(()=>{if(token===generation&&!ready)lost('Your friend could not connect.')},25000)});peer.on('error',error=>{if(token!==generation)return;if(host&&error.type==='unavailable-id'&&used.length<12){connect(true,'',used);return}lost(error.type==='peer-unavailable'?'Room not found. Keep the host’s page open.':'Online service unavailable.')});peer.on('disconnected',()=>{if(token===generation&&!ready)lost('Room service disconnected.')})}catch{if(token===generation)lost('Online play could not load.')}}
$('create').onclick=()=>connect(true);$('join').onclick=()=>{let word=$('roomCode').value.trim();try{if(word.includes('://'))word=new URL(word).searchParams.get('room')||''}catch{word=''}word=word.toLowerCase();if(!/^[a-z]{4,6}$/.test(word)){message('Enter a 4–6 letter room word or invite link.');return}connect(false,word)};
$('copy').onclick=async()=>{const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',room);try{await navigator.clipboard.writeText(u.href);message('Invite copied! Send it to your friend.')}catch{$('roomCode').value=u.href;$('roomCode').select();message('Copy the selected invite link.')}};
$('local').onclick=()=>{stop();mode='local';match=new Match2();role='host';flipped=false;message('Pass the device for private choices.');draw()};
$('leave').onclick=()=>{if(active()&&!game().result&&!confirm('Leave and end this match?'))return;stop();mode='idle';match=new Match2();flipped=false;selected=null;$('roomCode').value='';const u=new URL(location.href);u.searchParams.delete('room');history.replaceState(null,'',u);message('Create a room or enter your friend’s word.');draw()};
$('flip').onclick=()=>{flipped=!flipped;draw()};$('rematch').onclick=()=>act({type:'rematch'});$('resign').onclick=()=>{if(confirm('Resign this game?'))act({type:'resign'},viewer())};$('skip').onclick=()=>act({type:'skip'});$('whirlwind').onclick=()=>{if(selected&&confirm('Whirlwind destroys adjacent friendly and enemy pieces. Use it?'))act({type:'move',from:selected,to:selected,whirlwind:true})};
$('cancelPromotion').onclick=closePromotion;$('promotion').addEventListener('cancel',()=>{promotion=null});document.querySelectorAll('[data-piece]').forEach(b=>b.onclick=()=>{if(promotion)act({type:'move',...promotion,promotion:b.dataset.piece})});
$('privacyReady').onclick=()=>{localViewer=viewer();$('privacy').hidden=true};
for(const [id,name] of Object.entries(ARMIES)){const p=document.createElement('p');p.textContent=name+': '+ARMY_HELP[id];$('armyGuide').append(p)}
window.addEventListener('pagehide',stop);setInterval(()=>{if(mode!=='online'||!ready)return;const now=Date.now();if(now-lastSeen>90000){lost('Your friend stopped responding.');return}if(now-lastBeat>10000){lastBeat=now;send({type:'ping',version:24})}},5000);
$('loadingError').hidden=true;draw();const invite=new URL(location.href).searchParams.get('room');if(invite){$('roomCode').value=invite;message('Your friend invited you. Press Join room to play.')}
